name: Pipeline
on:
  pull_request:
    types: [opened, synchronize, reopened,closed]
    branches:
      - master

  jobs:
    build and deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up java
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'corretto'
        - name: Build with maven
          run: mvn clean install
        - name: Deploy to EB
          uses: einaregilsson/beanstalk-deploy@v20
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: 'Springboot-app'
            environment_name: 'Springboot-app-prod'
            version_label: 'v1-${{ github.sha }}'
            region: 'us-east-1'